defaults:
  # AWS credentials (leave these blank if just running the server)
  aws:
    accessKeyId:        '...'
    secretAccessKey:    '...'
    region:             us-west-2
  # Taskcluster credentials with
  # - "auth:azure-table-access:jungle/TestWorkerTypes"
  # - "auth:azure-table-access:jungle/TestWorkerSecrets"
  taskcluster:
    credentials:
      clientId:         '...'
      accessToken:      '...'
  # an azure account for blob storage (which can be the same)
  azureBlob:
    accountName:        jungle
    accountKey:         '...'
  # pulse credentials - see http://pulseguardian.mozilla.org/
  pulse:
    username:           '...'
    password:           '...'
